export const fields = [
    "area",
    "room",
    "year",
    "basement",
    "fitted_kitchen",
    "terrasse",
    "equipment",
    "city_aachen ",
    "city_augsburg ",
    "city_berlin",
    "city_bielefeld ",
    "city_bl-baden-wuerttemberg",
    "city_bochum ",
    "city_bonn ",
    "city_braunschweig",
    "city_bremen ",
    "city_chemnitz-sachs ",
    "city_dortmund ",
    "city_dresden ",
    "city_duesseldorf ",
    "city_duisburg ",
    "city_essen ",
    "city_frankfurt-am-main",
    "city_gelsenkirchen ",
    "city_hamburg ",
    "city_hannover ",
    "city_karlsruhe ",
    "city_kiel ",
    "city_koeln ",
    "city_leipzig ",
    "city_mannheim ",
    "city_moenchengladbach",
    "city_muenchen ",
    "city_muenster ",
    "city_nuernberg ",
    "city_stuttgart ",
    "city_wiesbaden ",
    "city_wuppertal ",
    "efficiency_class_A",
    "efficiency_class_A+",
    "efficiency_class_B",
    "efficiency_class_C",
    "efficiency_class_D",
    "efficiency_class_E",
    "efficiency_class_F",
    "efficiency_class_G",
    "efficiency_class_H",
    "Category_Bungalow",
    "Category_Doppelhaushälfte",
    "Category_Einfamilienhaus",
    "Category_Mehrfamilienhaus",
    "Category_Reihenendhaus",
    "Category_Reihenmittelhaus",
    "Category_Stadthaus",
    "Category_Villa",
    "Category_Zweifamilienhaus",
    "model_middle",
    "model_new",
    "model_old"
 ]


 module.exports.fields;